name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t 160487/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true 160487/react-test npm test

      - run: docker build -t 160487/multi-client ./client
      - run: docker build -t 160487/multi-nginx ./nginx
      - run: docker build -t 160487/multi-server ./server
      - run: docker build -t 160487/multi-worker ./worker

      - run: docker push 160487/multi-client
      - run: docker push 160487/multi-nginx
      - run: docker push 160487/multi-server
      - run: docker push 160487/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: MultiDocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-515121257519
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip